### PR TITLE
Retrieve attributes using super instead of hard-coding

### PR DESCRIPTION
**Pull request by Brobin**
You left a comment wanting to do it programmatically, and I found a way!

``` python
>>> from records import Record
>>> record = Record(['id','name'],[2,'Tobin'])
>>> dir(record)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__',
 '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__',
 '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__',
 '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__',
 '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_keys', '_values',
 'as_dict', 'dataset', 'export', 'get', 'id', 'keys', 'name', 'values']
```

### CODE REVIEW

**Comment by kennethreitz** [comment]
I swear I tried this, 100 different ways.

**Comment by Phrohdoh** [comment]
What is preventing this from being merged?

**Comment by kennethreitz** [comment]
Needs to be tested.

**Comment by Brobin** [comment]
I included a unit test. Does it not cover everything?

**Comment by kennethreitz** [comment]
I need to run the tests :)

**Comment by Phrohdoh** [comment]
Works for me, but no output at all is a bit unusual IMO.

```python
(venv_records) tmba:records thill $ python tests/test_records.py
(venv_records) tmba:records thill $ echo $?
0
```

**Comment by kennethreitz** [comment]
I'll just trust that this works. :)

**Pull request merged**
