### PR TITLE
support namedtuple rows as an alternative to dicts

### PR DESCRIPTION
**Pull request by btubbs**
I'm a big fan of namedtuples for their safety, syntax, and performance benefits.  This pull request adds a cursor_factory kwarg to `Database.__init__` so users can pass in psycopg2.extras.NamedTupleCursor to opt in to getting namedtuples instead of dicts.

ResultSet.dataset is updated to handle both dict and namedtuple row types.

### CODE REVIEW

**Comment by kennethreitz** [comment]
I thought long and hard about using the `NamedTupleCursor` or not. I settled on not because I love good 'ol dictionaries. They're effectively the universal data type for me.

I don't think making this swappable is a good idea *yet*, until we have a better feel for where the module is headed. This might be a good time to switch to using SQLAlchemy, for example, to support multiple database types while keeping the same interface. If we were to do that, adding functionality like this would make more sense afterwards. 

Looking forward to hearing your thoughts.

**Comment by btubbs** [comment]
I'm unsure what you mean when you say "using SQLAlchemy".  Since it's so big it could mean a lot of things.  Perhaps just the engine bit?  Or engine plus sessions? Full blown ORM instances?

The records library seems to me like a good fit for cases where I may want to export data in bulk.  In the past, using SQLAlchemy for such cases has bitten me hard; profiling showed that most of our processing time and memory were being spent in various layers of the SQLAlchemy stack.  I still love SQLAlchemy for transactional CRUD stuff, but I'm wary of dragging it into cases where I'm dealing with hundreds or thousands of records at a time.

Personally, being Postgres-specific is no problem.  But I can see how a name like 'records' could make people want something more agnostic and push you in the SQLAlchemy direction.

I'm not using records in any projects yet, so it's no big pain if the namedtuple support is rejected.  If I *were* to use it, I'd probably use a namedtuple fork.

All that said, thanks for putting this out!  It fills a nice niche.

**Comment by kennethreitz** [comment]
It would likely be the lowest level possible of integration, just to provide a universal connection to different database types. 

Auto-loading table classes are tempting, but if you want to do that, you should be using SQLAlchemy. 

------------------------------

Bulk data export is an excellent use case — I hadn't thought of that much. So, your interest in named tuples is purely for memory conservation? Is memory an issue if you're iterating over the (currently dictionary) rows, one at a time?

**Comment by btubbs** [comment]
Not just memory conservation.  I like attribute-style syntax.  And I *really* like that namedtuples' immutability can prevent unexpected mutations of the data as it moves through my app.

**Comment by kennethreitz** [comment]
fozendict!

Your thoughts are duly noted. Much to consider.

**Comment by kennethreitz** [comment]
There's a good chance I may merge this pull request. I received lots of feedback that users would prefer Records to return NamedTuples instead of Dicts.

**Comment by whit537** [comment]
!m @btubbs :-)

**Comment by kennethreitz** [comment]
Ended up writing my own class that uses `__slots__`, provides attrs for all values, supports non-alphanumeric fields, and dictionary-style lookups. I'm much happier with this implementation.

**Pull request merged**
