### PR TITLE
Add title and extension to license

### PR DESCRIPTION
**Pull request by waldyrious**
The title is not strictly required, but it's useful metadata, and part of the recommended license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license)

The extension helps with the display of the license on github (it activates text wrapping)

### CODE REVIEW

**Comment by waldyrious** [comment]
@kennethreitz any feedback?

**Comment by kennethreitz** [comment]
I don't find this useful. But, thank you :)

**Comment by waldyrious** [comment]
I respect your decision, but I'd me remiss if I didn't present the reasoning in more detail. Paraphrasing what I said [elsewhere](https://github.com/j256/ormlite-core/issues/82):

> While not required, there are various ways that adding the title can be useful. One is to make it clearer what license is actually being used (e.g. to quickly verify whether a project's license is among those vetted by the relevant FOSS organizations). It also improves searching (especially since licenses often use very similar language). Additionally, this can serve as a fast early check for content-based license matchers. And I'm sure there are other reasons I'm missing.

**Comment by kennethreitz** [comment]
Oh, I fully understand the reasoning. I actually prefer that people respect the actual text of license, and the name of the source of the text is a distraction from that.

The metadata is available elsewhere in the project (in setup.py).

I may change my mind later.

**Comment by waldyrious** [comment]
Got it. I just wanted to make sure the omission was intentional even considering those potential downsides 👍

**Comment by waldyrious** [comment]
By the way, would you be ok with just adding the extension? The way the license is currently displayed on the Github interface is quite inconvenient, and adding the extension would activate text wrapping.

**Comment by kennethreitz** [comment]
Nope.Thank you for the suggestion, though.

**Comment by kennethreitz** [comment]
Line-wrapping could be manually added, though.

**Comment by waldyrious** [comment]
> Line-wrapping could be manually added, though.

Right, that works too. I'll send another PR then.

**Comment by kennethreitz** [comment]
I appreciate your diligence. I'm extremely picky and intentional about this stuff :)

**Comment by waldyrious** [comment]
I can tell :) Thanks for bearing with me, and btw I'm glad this exchange is now on record, as it makes your intentionality explicit ;)

**Comment by kennethreitz** [comment]
Of course, little of it matters at all. I just have strong preferences.

**Pull request closed without merging**
