### PR TITLE
documentation update. as_dict and as_ordereddict are kwargs now

### PR DESCRIPTION
**Pull request by johnwheeler**

### CODE REVIEW

**Comment by Brobin** [comment]
:+1: This confused me for a little bit, had to look at the code to find the change.

**Comment by Brobin** [comment]
@kennethreitz Why was this changed? It seems more intuitive to have the Api similar for both `Record` and `RecordCollection`.

**Comment by Brobin** [comment]
Irrelevant as of d9a5396c1dee5f848ee997a440d4a4f2d9158823. Api was fixed to match documentation.

**Comment by kennethreitz** [comment]
[Documentation Driven Development](http://www.kennethreitz.org/essays/how-i-develop-things-and-why)! Thanks for the contribution, @johnwheeler.

**Comment by Brobin** [comment]
Wow, that's great!

**Pull request closed without merging**
