### PR TITLE
Branch for console application

### PR DESCRIPTION
**Pull request by andrew-tifon**
This branch will be used to work on the console version of the library

### CODE REVIEW

**Comment by Brobin** [comment]
Might be better to use [optparse](https://docs.python.org/3/library/optparse.html) to handle parsing of command line options and help messages.

```python
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-p", "--path", dest="path",
                  help=" The path to the database file .sql. Example 'path/test.sql'")
parser.add_option("-h", "--host", dest="host", default="localhost",
                  help="It's used to connect to a database, the default 'localhost'")
...
```

**Comment by andrew-tifon** [comment]
and will in the future, now it is necessary to determine the commands

**Comment by andrew-tifon** [comment]
@Brobin Now you need to determine the case in the future will be through optparse or argparse )

**Comment by Brobin** [comment]
True, looks like `argparse` might be the better option as it will get more future support. I was just pointing out that an argument parsing library of some sort should be used :)

**Comment by andrew-tifon** [comment]
Yes, of course, one of the command line will be used by libraries

**Comment by kennethreitz** [comment]
I have this part covered, actually!  https://github.com/kennethreitz/records/tree/cli

**Comment by kennethreitz** [comment]
Thanks for initiating this work, though! I'm just very opinionated about CLI stuff and want to do it myself :)
Collaboration is welcome, of course, as always!

**Pull request closed without merging**
