### PR TITLE
Disable SQLAlchemy connection pooling

### PR DESCRIPTION
**Pull request by RazerM**
The `Database` class provides no way to use it, and the current
implementation means that a connection is held by the pool even after
`db.close()`.

See also #67.

### CODE REVIEW

**Comment by kennethreitz** [comment]
aren't there major advantages to using the connection pooling with the current implementation?

**Comment by RazerM** [comment]
No, `Database` creates an engine then immediately asks that engine for a connection:

```python
        self._engine = create_engine(self.db_url, **kwargs)

        # Connect to the database.
        self.db = self._engine.connect()
```

Later, `Database.close` returns that connection to the pool. This means that the engine held by `Database` has a connection open for as long as it lives, even after calling `close`.

Connection pooling doesn't help since within the lifecycle of `Database`, one connection is checked out, then later returned.

**Comment by dmitrytokarev** [comment]
@RazerM please resolve conflicts. then we can ping Kenneth to merge this

**Comment by dmitrytokarev** [comment]
@kennethreitz could you review this PR?

**Comment by kennethreitz** [comment]
Sounds like we should fix `db.close()` then

**Comment by RazerM** [comment]
The way to fix `db.close()` is by not creating a connection pool that isn't used. It's only keeping a connection open because `create_engine`'s default arguments include `pool_size=5`, which is "the number of connections to keep open inside the connection pool".

**Comment by kennethreitz** [comment]
One of the goals of this library was to provide proper connection pooling, @RazerM. It sounds like I messed that up. Can we fix that easily?

**Pull request closed without merging**
