### PR TITLE
add support for bulk insert and update.

### PR DESCRIPTION
**Pull request by restran**
the method `query` can be used to insert or update data by sql, but works for only one row data.  

```py
def query(self, query, fetchall=False, **params):
    ...
```

i add the method to bulk insert and update.

```py
    def in_bulk(self, sql, *multiparams):
        """Bulk insert or update."""
        self.db.execute(text(sql), *multiparams)
```

### CODE REVIEW

**Comment by kennethreitz** [comment]
I don't understand this :)

@jasonmeyers? :)

**Comment by kennethreitz** [comment]
I don't understand this :)

@jasonamyers?

**Comment by jasonamyers** [comment]
This is the way of doing http://docs.sqlalchemy.org/en/latest/core/tutorial.html#executing-multiple-statements but in records. I think it's a nifty add, it lets you pass a list of parameter dictionaries. that will result in a bulk action.   It works for insert, update and delete.

**Comment by kennethreitz** [comment]
@jasonamyers thanks so much for your feedback! in over my head :)

**Comment by jasonamyers** [comment]
Happy to look. You've done fantastic work here. Not over your head at all, just glancing in a different direction.

**Pull request merged**
